### ISSUE TITLE
full size images do not seem to be caching properly

### ISSUE THREAD

**Issue by grundoon** [RangerRick/CruiseMonkey#100]
As noted by lila, embiggening images can take a while, but subsequent accesses have variable load times, sometimes longer than the first access. From watching the device within Xcode, it appears that /tmp gains an image each time an enlargement is requested, even when repeatedly selecting the same image.

(It would appear that something ain't kosher with 'check for existing'.)

**Comment by RangerRick** [comment]
I think my caching is fighting with the plugin's caching.  It wants to re-download to /tmp every time, but I can already create or find a local version of it with my cache tools.  I'll look at forking their plugin to avoid network round-trips if unnecessary.
