### ISSUE TITLE
Adding Event - Does not appear in list

### ISSUE THREAD

**Issue by hendusoone** [RangerRick/CruiseMonkey#110]
After adding a non-public shadow cruise event, it does not show up in the My Events list. All events lists are currently blank.

LG G4, Android 5.1, CM 2016.1.0 (build 40400)

**Comment by RangerRick** [comment]
Oh!  You're on build 40400, you're lucky it loaded at all.  Could you update to 40401 and tell me if it still happens?  40401 was specifically a fix for the event view.

**Comment by hendusoone** [comment]
It's working on 40401! Closing.
