### ISSUE TITLE
Time-based navigation auto-scroll

### ISSUE THREAD

**Issue by brianjgeiger** [RangerRick/CruiseMonkey#16]
Have views with day-based navigation automatically scroll to the present, so you see what events are coming up or happening now. This would combine nicely with the collapsible days.

**Comment by RangerRick** [comment]
This is working in CM2016

**Comment by brianjgeiger** [comment]
:tada:

**Comment by RangerRick** [comment]
Oop, actually, this is slightly different than what I've implemented.  I just have the "scroll to now" button.  It would be really easy to do this though, I'll make sure it goes in the next beta.

**Comment by brianjgeiger** [comment]
Cool, thanks. :)
