### ISSUE TITLE
Editing custom event causes duplicate event to be created.

### ISSUE THREAD

**Issue by pneumaticdeath** [RangerRick/CruiseMonkey#43]
I created an event "Fun with Land Sways" (spanning multiple days, though I don't know if that matters.), and later edited the event times.  When I went back later, there were now two events, one with the old time and one with the new.

**Comment by RangerRick** [comment]
Fixed in 4.9.2.  Released to the Google Play store, and headed to iOS testing as soon as Apple approves it.
