### ISSUE TITLE
CM would not remember user's settings changes

### ISSUE THREAD

**Issue by tasermonkey** [RangerRick/CruiseMonkey#46]
Since last year we had to have people change from the DNS to the IP address, this became a problem.  Basically if the user closed the application, on next launch it would revert the changes the user used, and return to the "On A Boat" default.

**Comment by RangerRick** [comment]
This is a Cordova bug in attempting to use localStorage for saving configuration data.  Apparently (at least on iOS) localStorage is eligible for purging when memory is low at any time.

CruiseMonkey 2016 now has a file-based persister that I've written for all caching and configuration, so it should no longer be an issue.
