### ISSUE TITLE
THO Request: Schedule Updates

### ISSUE THREAD

**Issue by rgorski** [RangerRick/CruiseMonkey#48]
From discussions with THO, it would be great if there was some way to add/edit/update the Official and Unofficial event lists while on-board, that isn't too onerous on any one person. Does not need to be in the app, even a web page behind a self-signed SSL with a login that just shows the records and allows field inserts/edits. Doesn't need to be CM-specific, even something that's similar to PHPMySQL would probably work.

**Comment by RangerRick** [comment]
The new CruiseMonkey supports this.  Any user that is an "admin" user in Twit-Arr is able to create/edit/delete "official" events from CruiseMonkey.

If I have time I may write a quick-and-dirty standalone editing UI, but it's definitely a stretch goal for this year.  At least now we can give the people managing the newsletter admin access so they can make sure events are kept up-to-date.
