### ISSUE TITLE
Unable to view cruisemonkey website in Safari browser on iOS

### ISSUE THREAD

**Issue by realfakegeekgrl** [RangerRick/CruiseMonkey#52]
I went to the website indicated on the forums in the Safari browser on my iPhone, but the page just loads blank.

**Comment by realfakegeekgrl** [comment]
Correction - I also cannot get it to load in Safari on OSX either.  It appears to work in Firefox on OSX fine though.

**Comment by RangerRick** [comment]
I think all browser versions are affected to varying degrees depending on how well they handle certain exceptions.  It appears that I'm hitting some kind of Angular/Ionic bug going by the javascript logs.  I will investigate further.

**Comment by RangerRick** [comment]
I believe I have this working pretty well now.  I'm marking as closed, but please let me know if you still have issues with the browser version.
