### ISSUE TITLE
Login Fail on Android

### ISSUE THREAD

**Issue by abydos641** [RangerRick/CruiseMonkey#54]
Followed the directions to create new account located here:
http://www.jonathancoulton.com/forums/index.php?p=%2Fdiscussion%2F2448%2Ftwit-arr-and-cruisemonkey-2016

Downloaded app via PlayStore (confirmed it is the latest version w/ @RangerRick )

Attempted to login.

Login Failed alert pops up.

Ran adb logcat and emailed .txt to @RangerRick 

Device: Moto X
OS: 5.1 Lollipop

**Comment by chinkleDC** [comment]
I had the same issue.  Device: Samsung Galaxy S4; OS: 5.0.1 Lollipop

**Comment by dwatney** [comment]
Ditto for me and my wife. Both using Samsung Galaxy S6, Android 5.1.1

**Comment by RangerRick** [comment]
Does anyone with Android have the ability to side-load and can tell me if this build works?  http://ranger.befunk.com/temp/cruisemonkey/android-release-signed.apk

**Comment by dwatney** [comment]
I got "Login failed." again. 
    
    Just to make sure it is correct, the Twit-Arr URL listed is
    https://cm.raccoonfink.com/
    
    On 1/21/2016 2:40 PM, Benjamin Reed
      wrote:
    
    
      Does anyone with Android have the ability to side-load and can
        tell me if this build works? http://ranger.befunk.com/temp/cruisemonkey/android-release-signed.apk
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by abydos641** [comment]
Hey everyone,

Try to login now. We've tested and confirmed that the Android login issue should be resolved (it is on my device).

Sound out if you're still experiencing problems. Thanks!

**Comment by RangerRick** [comment]
Turns out it was a bug in the certificate on the server.  If you log in again it should work.
