### ISSUE TITLE
Cryptic Error Trying to Create an Event

### ISSUE THREAD

**Issue by AgentPayne** [RangerRick/CruiseMonkey#67]
There's a "Make Official?" checkbox on the "Add an Event" form but trying to create an official event returns a generic error (Failed to add event:[object Object])  I'm assuming that's because I don't have the rights to create official events but a message explicitly stating that would be less confusing. Security trimming that checkbox from the UI would be even better.

**Comment by RangerRick** [comment]
Can you tell me what build you're running?  I believe that should be fixed in build 40365.  (You can see the build number in Ship -> About CruiseMonkey)

**Comment by AgentPayne** [comment]
I was on 40361. In 40365 the "Make Official?" Check box isn't visible.

**Comment by RangerRick** [comment]
OK, good.  It shouldn't let you make official events unless you're an admin.  :)

Marking as closed.
